version: 1.0.0+{build}

environment:
  matrix:

    - PHP_VERSION: 7.3
      VC_VERSION: 15
      BUILD_TYPE: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - PHP_VERSION: 7.3
      VC_VERSION: 15
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  PHP_SDK_VERSION: 2.1.9
  PECL_PSR_VERSION: 0.6.1
  ZEPHIR_PARSER_VERSION: 1.2.0
  ZEPHIR_PARSER_RELEASE: 454

matrix:
  fast_finish: true

cache:
  - 'C:\Downloads -> .appveyor.yml'

clone_depth: 1
clone_folder: C:\Projects\php-appveyor

platform:
  - x86
  - x64

branches:
  only:
    - master
    - development

init:
  - ps: $DebugPreference = "SilentlyContinue" # Continue

install:
  - ps: Import-Module .\php-appveyor.psm1

  - ps: InstallPhpSdk     $Env:PHP_SDK_VERSION $Env:VC_VERSION $Env:PLATFORM
  - ps: InstallPhp        $Env:PHP_VERSION $Env:BUILD_TYPE $Env:VC_VERSION $Env:PLATFORM
  - ps: InstallPhpDevPack $Env:PHP_VERSION $Env:BUILD_TYPE $Env:VC_VERSION $Env:PLATFORM

  - ps: TuneUpPhp
  - ps: InstallComposer

before_build:
  - ps: >-
      InstallPeclExtension `
        -Name       psr `
        -Version    $Env:PECL_PSR_VERSION `
        -PhpVersion $Env:PHP_VERSION `
        -BuildType  $Env:BUILD_TYPE `
        -VC         $Env:VC_VERSION `
        -Platform   $Env:PLATFORM

  - ps: >-
      InstallZephirParser `
        -Version    $Env:ZEPHIR_PARSER_VERSION `
        -BuildId    $Env:ZEPHIR_PARSER_RELEASE `
        -PhpVersion $Env:PHP_VERSION `
        -BuildType  $Env:BUILD_TYPE `
        -VC         $Env:VC_VERSION `
        -Platform   $Env:PLATFORM

  - ps: EnablePhpExtension -Name psr
  - ps: EnablePhpExtension -Name zephir_parser -PrintableName "Zephir Parser"

build_script:
  - ps: (& C:\php\php.exe --ri psr)
  - ps: (& C:\php\php.exe --ri "Zephir Parser")

test_script:
  - cmd: 'composer --help'

after_test:
  - ps: >-
      PrepareReleasePackage `
        -PhpVersion     $Env:PHP_VERSION `
        -BuildType      $Env:BUILD_TYPE `
        -Platform       $Env:PLATFORM `
        -ZipballName    php-appveyor `
        -ReleaseFiles   LICENSE,README.adoc `
        -ConverMdToHtml $true

artifacts:
  - path: '.\php-appveyor.zip'
    type: zip
    name: php-appveyor
